CREATE A CLASS CALLED CARS WITH THE FOLLOWING ATTRIBUTSE
#MODEL,YEAR OF MANUFACTURING,TYPE,COLOR
#CREATE METHOD OF PRINT
#"MY DREAM CAR IS ....MANUFUCTURES IN .... BEING A ...TYPE,..COLOR"
#INITIALIZE WITH AT LEAST 5 OBJECT